<?php

namespace CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefUserTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefUserTypeRepository extends EntityRepository
{
}
